### ISSUE TITLE
适配性讨论

### ISSUE THREAD

**Issue by liuly0218** [cunxinaimei/AdaptiveAnkoComponent#1]
之前也一直测试鸿洋的AndroidAutoLayout，包括其他适配方案，发现这种适配在手机上效果不错，但是相同布局在平板上就适配不好，因为适配的核心还是等比例放大缩小吧，手机的布局放在平板上感觉严重放大，请问有没有可以同时适配手机和平板设备的方案？

**Comment by nobeginning** [comment]
手机和平板设备屏幕大小差太多了，通常情况下如果想要体验比较好的话，最好还是针对手机和平板做不同的UI和交互设计，这种等比放大缩小的方案确实是不适用的。
当然，如果页面业务逻辑相同，只是UI展示不一样的话，可以考虑一下MVP，Activity作为P层，V层接口抽象出来之后根据设备屏幕尺寸做不同的实现，这样就可以做到P层复用。
