### ISSUE TITLE
  java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;

### ISSUE THREAD

**Issue by star-andy** [cunxinaimei/AdaptiveAnkoComponent#3]
依赖到java项目中会提示这个kotlin得错误

**Comment by nobeginning** [comment]
依赖项中增加：
implementation 'com.mapzen:on-the-road:1.3.1'

[https://mvnrepository.com/artifact/com.mapzen/on-the-road](url)
